# ---------------------------------------------------------------------------
# Autolab Stage Registry (workflow.yaml)
# ---------------------------------------------------------------------------
# Single source of truth for per-stage metadata: prompt files, required
# tokens, required output artifacts, verifier categories, successor stages,
# and stage classifications.
#
# The orchestrator, prompt renderer, and verification system can all read
# this file to avoid hard-coded stage-specific logic scattered across the
# codebase.  Runtime overrides (e.g. verifier_policy.yaml) take precedence
# where applicable.
#
# Pattern Path Convention:
#   Paths containing <RUN_ID>, <ITERATION_ID>, or similar angle-bracket
#   tokens are *pattern paths* -- templates resolved at runtime. They are
#   NOT literal filesystem paths.
#   Example: required_outputs: [runs/<RUN_ID>/run_manifest.json]
#   At runtime <RUN_ID> is replaced with the actual run ID from state,
#   e.g. runs/20260218T160045Z/run_manifest.json
#
# Classification note:
#   classifications.decision means "this stage is selectable as a decision
#   target (e.g., decide_repeat.decision_map)", not "this stage itself makes
#   a branching decision".
# ---------------------------------------------------------------------------

schema_version: "1.0"

stages:
  hypothesis:
    prompt_file: stage_hypothesis.md
    required_tokens: [iteration_id, iteration_path, hypothesis_id]
    required_outputs: [hypothesis.md]
    next_stage: design
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: false
      env_smoke: false
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: true
      runner_eligible: true

  design:
    prompt_file: stage_design.md
    required_tokens: [iteration_id, iteration_path, hypothesis_id]
    required_outputs: [design.yaml]
    next_stage: implementation
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: false
      env_smoke: false
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: true
      runner_eligible: true

  implementation:
    prompt_file: stage_implementation.md
    required_tokens: [iteration_id, iteration_path]
    required_outputs: [implementation_plan.md]
    next_stage: implementation_review
    verifier_categories:
      tests: false
      dry_run: true   # Capability flag. Actual requirement controlled by verifier_policy.yaml
      schema: true
      prompt_lint: true
      consistency: false
      env_smoke: false
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  implementation_review:
    prompt_file: stage_implementation_review.md
    required_tokens: [iteration_id, iteration_path]
    required_outputs: [implementation_review.md, review_result.json]
    next_stage: launch
    verifier_categories:
      tests: false
      dry_run: true
      schema: true
      prompt_lint: true
      consistency: true
      env_smoke: true
      docs_target_update: true
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  launch:
    prompt_file: stage_launch.md
    required_tokens: [iteration_id, iteration_path, run_id]
    required_outputs: [runs/<RUN_ID>/run_manifest.json]
    next_stage: slurm_monitor
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: true
      env_smoke: true
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  slurm_monitor:
    prompt_file: stage_slurm_monitor.md
    required_tokens: [iteration_id, iteration_path, run_id]
    required_outputs: [runs/<RUN_ID>/run_manifest.json]
    next_stage: extract_results
    verifier_categories:
      tests: false
      dry_run: false
      schema: false
      prompt_lint: false
      consistency: false
      env_smoke: true
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  extract_results:
    prompt_file: stage_extract_results.md
    required_tokens: [iteration_id, iteration_path, run_id]
    required_outputs: [runs/<RUN_ID>/metrics.json, analysis/summary.md]
    next_stage: update_docs
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: true
      env_smoke: true
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  update_docs:
    prompt_file: stage_update_docs.md
    required_tokens: [iteration_id, iteration_path, run_id]
    required_outputs: [docs_update.md]
    next_stage: decide_repeat
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: true
      env_smoke: false
      docs_target_update: true
    classifications:
      active: true
      terminal: false
      decision: false
      runner_eligible: true

  decide_repeat:
    prompt_file: stage_decide_repeat.md
    required_tokens: [iteration_id, iteration_path]
    required_outputs: [decision_result.json]
    next_stage: ""
    decision_map:
      design: design
      hypothesis: hypothesis
      stop: stop
      human_review: human_review
    verifier_categories:
      tests: false
      dry_run: false
      schema: true
      prompt_lint: true
      consistency: true
      env_smoke: false
      docs_target_update: false
    classifications:
      active: true
      terminal: false
      decision: true
      runner_eligible: true

  human_review:
    prompt_file: stage_human_review.md
    required_tokens: []
    required_outputs: []
    next_stage: ""
    verifier_categories:
      tests: false
      dry_run: false
      schema: false
      prompt_lint: false
      consistency: false
      env_smoke: false
      docs_target_update: false
    classifications:
      active: false
      terminal: true
      decision: true
      runner_eligible: false

  stop:
    prompt_file: stage_stop.md
    required_tokens: []
    required_outputs: []
    next_stage: ""
    verifier_categories:
      tests: false
      dry_run: false
      schema: false
      prompt_lint: false
      consistency: false
      env_smoke: false
      docs_target_update: false
    classifications:
      active: false
      terminal: true
      decision: true
      runner_eligible: false
